//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiaryHoneyProduction
    {
        public int ProductionId { get; set; }
        public Nullable<int> ApiaryId { get; set; }
        public Nullable<int> ProductionPeriodId { get; set; }
        public Nullable<int> ProducedHoneyType { get; set; }
        public Nullable<int> HoneyDistributionType { get; set; }
        public Nullable<decimal> ProductionAmount { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
    }
}
