//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiaryBeehiveDiseas
    {
        public int Id { get; set; }
        public Nullable<int> DiseaseId { get; set; }
        public Nullable<int> BeehiveId { get; set; }
        public string BeehiveCode { get; set; }
        public Nullable<int> ProductionPeriodId { get; set; }
        public string TreatmentMethods { get; set; }
    }
}
