//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiaryBeehive
    {
        public int BeehiveId { get; set; }
        public Nullable<int> ApiaryId { get; set; }
        public string BeehiveBarcode { get; set; }
        public Nullable<int> BeehiveType { get; set; }
        public Nullable<int> BeehiveBuildingMaterial { get; set; }
        public string BeehiveTechnologyInfrastructure { get; set; }
    }
}
