//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beekeeper
    {
        public System.Guid BeekeeperId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentityNumber { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<short> ExperienceTime { get; set; }
        public Nullable<int> EducationLevel { get; set; }
        public Nullable<bool> CertificationInfo { get; set; }
        public string AssociationMembership { get; set; }
        public string BusinessNumber { get; set; }
        public Nullable<int> BeekeepingPurposeType { get; set; }
        public Nullable<int> BeekeepingType { get; set; }
    }
}
