//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoneyTest
    {
        public int HoneyTestId { get; set; }
        public Nullable<int> ApiaryId { get; set; }
        public Nullable<int> HoneyTestItemId { get; set; }
        public string HoneyTestItemValue { get; set; }
    }
}
