//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPeriod
    {
        public int ProductionPeriodId { get; set; }
        public string ProductionPeriodTitle { get; set; }
        public Nullable<System.DateTime> ProductionPeriodStartDate { get; set; }
        public Nullable<System.DateTime> ProductionPeriodEndDate { get; set; }
    }
}
