//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOP4HoneyChains.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOP4HoneyChainsDbEntities : DbContext
    {
        public TOP4HoneyChainsDbEntities()
            : base("name=TOP4HoneyChainsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apiary> Apiaries { get; set; }
        public virtual DbSet<ApiaryBeehiveDiseas> ApiaryBeehiveDiseases { get; set; }
        public virtual DbSet<ApiaryBeehive> ApiaryBeehives { get; set; }
        public virtual DbSet<ApiaryBeehivesFeedingProgram> ApiaryBeehivesFeedingPrograms { get; set; }
        public virtual DbSet<ApiaryHoneyProduction> ApiaryHoneyProductions { get; set; }
        public virtual DbSet<BeehiveBuildingMaterial> BeehiveBuildingMaterials { get; set; }
        public virtual DbSet<BeehiveDiseas> BeehiveDiseases { get; set; }
        public virtual DbSet<BeehiveLocationType> BeehiveLocationTypes { get; set; }
        public virtual DbSet<BeehiveType> BeehiveTypes { get; set; }
        public virtual DbSet<Beekeeper> Beekeepers { get; set; }
        public virtual DbSet<BeekeepingPurposeType> BeekeepingPurposeTypes { get; set; }
        public virtual DbSet<BeekeepingType> BeekeepingTypes { get; set; }
        public virtual DbSet<EducationLevel> EducationLevels { get; set; }
        public virtual DbSet<FeedingMaterial> FeedingMaterials { get; set; }
        public virtual DbSet<HoneyDistributionType> HoneyDistributionTypes { get; set; }
        public virtual DbSet<HoneyTestItem> HoneyTestItems { get; set; }
        public virtual DbSet<HoneyTest> HoneyTests { get; set; }
        public virtual DbSet<HoneyType> HoneyTypes { get; set; }
        public virtual DbSet<ProductionPeriod> ProductionPeriods { get; set; }
    }
}
